WEATHER_ICON_MAPPING = {
  :day => {
    'freezing_rain_heavy': :day_rain_mix,
    'freezing_rain':  :day_rain_mix,
    'freezing_rain_light':  :day_rain_mix,
    'freezing_drizzle': :day_rain_mix,
    'ice_pellets_heavy': :day_hail,
    'ice_pellets': :day_hail,
    'ice_pellets_light': :day_hail,
    'snow_heavy': :day_snow,
    'snow': :day_snow,
    'snow_light': :day_snow,
    'flurries': :day_snow_wind,
    'tstorm': :day_thunderstorm,
    'rain_heavy': :day_rain,
    'rain': :day_rain,
    'rain_light': :day_rain,
    'drizzle': :day_rain,
    'fog_light': :day_fog,
    'fog': :day_fog,
    'cloudy': :cloudy,
    'mostly_cloudy': :cloud,
    'partly_cloudy': :day_cloudy,
    'mostly_clear': :day_sunny_overcast,
    'clear': :day_sunny,
  },
  :night => {
    'freezing_rain_heavy': :night_rain_mix,
    'freezing_rain':  :night_rain_mix,
    'freezing_rain_light':  :night_rain_mix,
    'freezing_drizzle': :night_rain_mix,
    'ice_pellets_heavy': :night_hail,
    'ice_pellets': :night_hail,
    'ice_pellets_light': :night_hail,
    'snow_heavy': :night_snow,
    'snow': :night_snow,
    'snow_light': :night_snow,
    'flurries': :night_snow_wind,
    'tstorm': :night_thunderstorm,
    'rain_heavy': :night_rain,
    'rain': :night_rain,
    'rain_light': :night_rain,
    'drizzle': :night_rain,
    'fog_light': :night_fog,
    'fog': :night_fog,
    'cloudy': :cloudy,
    'mostly_cloudy': :cloud,
    'partly_cloudy': :night_cloudy,
    'mostly_clear': :night_partly_cloudy,
    'clear': :night_clear,
  }
}

